### ISSUE TITLE
einsum() operands do not broadcast with remapped shapes in render_warp.py

### ISSUE THREAD

**Issue by Seooooooogi** [songrise/AvatarCraft#9]
Thanks for great work!
To render articulated avatar, I tried yoga pose in AMASS SFU dataset.
Then encountered an error:

```
Traceback (most recent call last):
  File "render_warp.py", line 272, in <module>
    main(opt)
  File "render_warp.py", line 50, in main
    max_frames=opt.max_frames
  File "render_warp.py", line 176, in calc_local_trans
    concat_joints=True
  File "/workspace/jaeseok/avatarcraft/models/smpl.py", line 152, in verts_transformations
    return_T=True, concat_joints=concat_joints)
  File "/workspace/jaeseok/avatarcraft/models/smpl.py", line 396, in lbs
    v_delta = blend_shapes(betas, shapedirs)
  File "/workspace/jaeseok/avatarcraft/models/smpl.py", line 546, in blend_shapes
    blend_shape = torch.einsum('bl,mkl->bmk', [betas, shape_disps])
  File "/opt/conda/envs/craft/lib/python3.7/site-packages/torch/functional.py", line 406, in einsum
    return einsum(equation, *_operands)
  File "/opt/conda/envs/craft/lib/python3.7/site-packages/torch/functional.py", line 408, in einsum
    return _VF.einsum(equation, operands)  # type: ignore
einsum() operands do not broadcast with remapped shapes [original->remapped]: [1, 10]->[1, 1, 1, 10] [6890, 3, 300]->[1, 6890, 3, 300]
```

**Comment by 1211186431** [comment]
I have also encountered the same problem. Have you found a solution yet

**Comment by Seooooooogi** [comment]
> I have also encountered the same problem. Have you found a solution yet

In smpl.py, tensor shape_disps contains nothing after [:, :, 10:].
I solved the issue by adding shape_disps = shape_disps[:, :, :10]
![image](https://github.com/songrise/AvatarCraft/assets/93199081/a0536c98-95e6-4564-8380-5e1ac050c337)
So I close the issue.
